version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - nilerr

formatters:
  enable:
    - gofmt
    - goimports
